In [1]:
import pandas as pd

In [13]:
# importing data
all_words_df = pd.read_csv("/Users/iman/CPSC_Courses/CPSC393/CPSC393Final/Data/all_words.csv")
all_words_df.head()

      word   type
0    peeps  slang
1    compo  slang
2  hasbian  slang
3   mozzie  slang
4   soused  slang

In [14]:
spotify_artists_df = pd.read_csv("/Users/iman/CPSC_Courses/CPSC393/CPSC393Final/Data/spotify_artists.csv")
spotify_artists_df.head(2)

,Unnamed: 0,artist_popularity,followers,genres,id,name,track_id,track_name_prev,type
0,0,44,23230,"['sertanejo', 'sertanejo pop', 'sertanejo trad...",4mGnpjhqgx4RUdsIJiURdo,Juliano Cezar,0wmDmAILuW9e2aRttkl4aC,track_9,artist
1,1,22,313,[],1dLnVku4VQUOLswwDFvRc9,The Grenadines,4wqwj0gA8qPZKLl5WVqXml,track_30,artist

In [15]:
spotify_artists_df = spotify_artists_df.drop(['Unnamed: 0'], axis=1)
spotify_artists_df = spotify_artists_df.rename(columns = {'id':'artists_id', 'name':'artist_name'})
spotify_artists_df.head(2)

,artist_popularity,followers,genres,artists_id,artist_name,track_id,track_name_prev,type
0,44,23230,"['sertanejo', 'sertanejo pop', 'sertanejo trad...",4mGnpjhqgx4RUdsIJiURdo,Juliano Cezar,0wmDmAILuW9e2aRttkl4aC,track_9,artist
1,22,313,[],1dLnVku4VQUOLswwDFvRc9,The Grenadines,4wqwj0gA8qPZKLl5WVqXml,track_30,artist

In [16]:
spotify_artists_df = spotify_artists_df.drop(['track_name_prev', 'type', 'genres'], axis=1)
spotify_artists_df.head(2)

,artist_popularity,followers,artists_id,artist_name,track_id
0,44,23230,4mGnpjhqgx4RUdsIJiURdo,Juliano Cezar,0wmDmAILuW9e2aRttkl4aC
1,22,313,1dLnVku4VQUOLswwDFvRc9,The Grenadines,4wqwj0gA8qPZKLl5WVqXml

In [17]:
spotify_albums_df = pd.read_csv("/Users/iman/CPSC_Courses/CPSC393/CPSC393Final/Data/spotify_albums.csv")
spotify_albums_df.head(2)

,Unnamed: 0,album_type,artist_id,available_markets,external_urls,href,id,images,name,release_date,release_date_precision,total_tracks,track_id,track_name_prev,uri,type
0,0,single,3DiDSECUqqY1AuBP8qtaIa,"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",{'spotify': 'https://open.spotify.com/album/1g...,https://api.spotify.com/v1/albums/1gAM7M4rBwEb...,1gAM7M4rBwEbSPeAQR2nx1,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",If I Ain't Got You EP,2019-02-08,day,6,2iejTMy9XZ8Gaae0aQ2yl0,track_32,spotify:album:1gAM7M4rBwEbSPeAQR2nx1,album
1,1,album,6s1pCNXcbdtQJlsnM1hRIA,"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",{'spotify': 'https://open.spotify.com/album/4K...,https://api.spotify.com/v1/albums/4KfJZV7WfolY...,4KfJZV7WfolYlxBzOTo66s,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Shostakovich Symphony No.5 - Four Romances on ...,2019-03-01,day,8,1WQfghEjszJJ4H8MAWrQ2C,track_11,spotify:album:4KfJZV7WfolYlxBzOTo66s,album

In [18]:
spotify_albums_df = spotify_albums_df.drop(['Unnamed: 0'], axis=1)
spotify_albums_df = spotify_albums_df.rename(columns = {'id':'album_id', 'artist_id':'artists_id', 'name':'album_name'})
spotify_albums_df.head(2)

,album_type,artists_id,available_markets,external_urls,href,album_id,images,album_name,release_date,release_date_precision,total_tracks,track_id,track_name_prev,uri,type
0,single,3DiDSECUqqY1AuBP8qtaIa,"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",{'spotify': 'https://open.spotify.com/album/1g...,https://api.spotify.com/v1/albums/1gAM7M4rBwEb...,1gAM7M4rBwEbSPeAQR2nx1,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",If I Ain't Got You EP,2019-02-08,day,6,2iejTMy9XZ8Gaae0aQ2yl0,track_32,spotify:album:1gAM7M4rBwEbSPeAQR2nx1,album
1,album,6s1pCNXcbdtQJlsnM1hRIA,"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",{'spotify': 'https://open.spotify.com/album/4K...,https://api.spotify.com/v1/albums/4KfJZV7WfolY...,4KfJZV7WfolYlxBzOTo66s,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Shostakovich Symphony No.5 - Four Romances on ...,2019-03-01,day,8,1WQfghEjszJJ4H8MAWrQ2C,track_11,spotify:album:4KfJZV7WfolYlxBzOTo66s,album

In [19]:
spotify_albums_df = spotify_albums_df.drop(['album_type', 'available_markets', 'external_urls', 'href', 'images', 'release_date_precision', 'total_tracks', 'track_name_prev', 'uri', 'type'], axis=1)
spotify_albums_df.head(2)

,artists_id,album_id,album_name,release_date,track_id
0,3DiDSECUqqY1AuBP8qtaIa,1gAM7M4rBwEbSPeAQR2nx1,If I Ain't Got You EP,2019-02-08,2iejTMy9XZ8Gaae0aQ2yl0
1,6s1pCNXcbdtQJlsnM1hRIA,4KfJZV7WfolYlxBzOTo66s,Shostakovich Symphony No.5 - Four Romances on ...,2019-03-01,1WQfghEjszJJ4H8MAWrQ2C

In [20]:
spotify_tracks_df = pd.read_csv("/Users/iman/CPSC_Courses/CPSC393/CPSC393Final/Data/spotify_tracks.csv")
spotify_tracks_df.head(2)

,Unnamed: 0,acousticness,album_id,analysis_url,artists_id,available_markets,country,danceability,disc_number,duration_ms,...,preview_url,speechiness,tempo,time_signature,track_href,track_name_prev,track_number,uri,valence,type
0,0,0.294,0D3QufeCudpQANOR7luqdr,https://api.spotify.com/v1/audio-analysis/5qlj...,['3mxJuHRn2ZWD5OofvJtDZY'],"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",BE,0.698,1.0,235584.0,...,https://p.scdn.co/mp3-preview/1b05a902da3a251d...,0.0262,115.018,4.0,https://api.spotify.com/v1/tracks/5qljLQuKnNJf...,track_14,1.0,spotify:track:5qljLQuKnNJf4F4vfxQB0V,0.622,track
1,1,0.863,1bcqsH5UyTBzmh9YizdsBE,https://api.spotify.com/v1/audio-analysis/3VAX...,['4xWMewm6CYMstu0sPgd9jJ'],"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",BE,0.719,1.0,656960.0,...,https://p.scdn.co/mp3-preview/d8140736a6131cb5...,0.9220,115.075,3.0,https://api.spotify.com/v1/tracks/3VAX2MJdmdqA...,track_3,3.0,spotify:track:3VAX2MJdmdqARLSU5hPMpm,0.589,track

In [21]:
spotify_tracks_df = spotify_tracks_df.drop(['Unnamed: 0'], axis=1)
spotify_tracks_df = spotify_tracks_df.rename(columns = {'id':'track_id', 'popularity': 'track_popularity', 'name':'track_name'})
spotify_tracks_df.head(2)

,acousticness,album_id,analysis_url,artists_id,available_markets,country,danceability,disc_number,duration_ms,energy,...,preview_url,speechiness,tempo,time_signature,track_href,track_name_prev,track_number,uri,valence,type
0,0.294,0D3QufeCudpQANOR7luqdr,https://api.spotify.com/v1/audio-analysis/5qlj...,['3mxJuHRn2ZWD5OofvJtDZY'],"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",BE,0.698,1.0,235584.0,0.606,...,https://p.scdn.co/mp3-preview/1b05a902da3a251d...,0.0262,115.018,4.0,https://api.spotify.com/v1/tracks/5qljLQuKnNJf...,track_14,1.0,spotify:track:5qljLQuKnNJf4F4vfxQB0V,0.622,track
1,0.863,1bcqsH5UyTBzmh9YizdsBE,https://api.spotify.com/v1/audio-analysis/3VAX...,['4xWMewm6CYMstu0sPgd9jJ'],"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",BE,0.719,1.0,656960.0,0.308,...,https://p.scdn.co/mp3-preview/d8140736a6131cb5...,0.9220,115.075,3.0,https://api.spotify.com/v1/tracks/3VAX2MJdmdqA...,track_3,3.0,spotify:track:3VAX2MJdmdqARLSU5hPMpm,0.589,track

In [22]:
spotify_tracks_df.artists_id = spotify_tracks_df.artists_id.str.strip("[]")
spotify_tracks_df.artists_id = spotify_tracks_df.artists_id.str.strip("'")
spotify_tracks_df.head(2)

,acousticness,album_id,analysis_url,artists_id,available_markets,country,danceability,disc_number,duration_ms,energy,...,preview_url,speechiness,tempo,time_signature,track_href,track_name_prev,track_number,uri,valence,type
0,0.294,0D3QufeCudpQANOR7luqdr,https://api.spotify.com/v1/audio-analysis/5qlj...,3mxJuHRn2ZWD5OofvJtDZY,"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",BE,0.698,1.0,235584.0,0.606,...,https://p.scdn.co/mp3-preview/1b05a902da3a251d...,0.0262,115.018,4.0,https://api.spotify.com/v1/tracks/5qljLQuKnNJf...,track_14,1.0,spotify:track:5qljLQuKnNJf4F4vfxQB0V,0.622,track
1,0.863,1bcqsH5UyTBzmh9YizdsBE,https://api.spotify.com/v1/audio-analysis/3VAX...,4xWMewm6CYMstu0sPgd9jJ,"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",BE,0.719,1.0,656960.0,0.308,...,https://p.scdn.co/mp3-preview/d8140736a6131cb5...,0.9220,115.075,3.0,https://api.spotify.com/v1/tracks/3VAX2MJdmdqA...,track_3,3.0,spotify:track:3VAX2MJdmdqARLSU5hPMpm,0.589,track

In [23]:
spotify_tracks_df = spotify_tracks_df.drop(['acousticness', 'analysis_url', 'available_markets', 'country', 'danceability', 'disc_number', 'duration_ms', 'energy', 'href', 'instrumentalness', 'key', 'liveness', 'loudness', 'mode', 'playlist', 'preview_url', 'speechiness', 'tempo', 'time_signature', 'track_href', 'track_name_prev', 'track_number', 'uri', 'valence', 'type'], axis=1)
spotify_tracks_df.head(2)

,album_id,artists_id,track_id,lyrics,track_name,track_popularity
0,0D3QufeCudpQANOR7luqdr,3mxJuHRn2ZWD5OofvJtDZY,5qljLQuKnNJf4F4vfxQB0V,\r\n\r\nPerhaps I am bound to be restless\r\nA...,Blood,28.0
1,1bcqsH5UyTBzmh9YizdsBE,4xWMewm6CYMstu0sPgd9jJ,3VAX2MJdmdqARLSU5hPMpm,\r\nYour Gods and my Gods-do you or I know whi...,The Ugly Duckling,31.0

In [24]:
spotify_artists_df.head(2)

,artist_popularity,followers,artists_id,artist_name,track_id
0,44,23230,4mGnpjhqgx4RUdsIJiURdo,Juliano Cezar,0wmDmAILuW9e2aRttkl4aC
1,22,313,1dLnVku4VQUOLswwDFvRc9,The Grenadines,4wqwj0gA8qPZKLl5WVqXml

In [25]:
spotify_albums_df.head(2)

,artists_id,album_id,album_name,release_date,track_id
0,3DiDSECUqqY1AuBP8qtaIa,1gAM7M4rBwEbSPeAQR2nx1,If I Ain't Got You EP,2019-02-08,2iejTMy9XZ8Gaae0aQ2yl0
1,6s1pCNXcbdtQJlsnM1hRIA,4KfJZV7WfolYlxBzOTo66s,Shostakovich Symphony No.5 - Four Romances on ...,2019-03-01,1WQfghEjszJJ4H8MAWrQ2C

In [26]:
spotify_tracks_df.head(2)

,album_id,artists_id,track_id,lyrics,track_name,track_popularity
0,0D3QufeCudpQANOR7luqdr,3mxJuHRn2ZWD5OofvJtDZY,5qljLQuKnNJf4F4vfxQB0V,\r\n\r\nPerhaps I am bound to be restless\r\nA...,Blood,28.0
1,1bcqsH5UyTBzmh9YizdsBE,4xWMewm6CYMstu0sPgd9jJ,3VAX2MJdmdqARLSU5hPMpm,\r\nYour Gods and my Gods-do you or I know whi...,The Ugly Duckling,31.0

In [27]:
extended_tracks_df = pd.merge(spotify_tracks_df, spotify_artists_df[['artists_id', 'artist_popularity']], on='artists_id')
extended_tracks_df.head()

,album_id,artists_id,track_id,lyrics,track_name,track_popularity,artist_popularity
0,0D3QufeCudpQANOR7luqdr,3mxJuHRn2ZWD5OofvJtDZY,5qljLQuKnNJf4F4vfxQB0V,\r\n\r\nPerhaps I am bound to be restless\r\nA...,Blood,28.0,28
1,3wIjGVauUxR4c3NvnQZ0Jo,3mxJuHRn2ZWD5OofvJtDZY,3THTkAwJOsmxgizvYkBNRI,\r\n\r\nMuch better in my day\r\nMuch better i...,Jericho,37.0,28
2,1bcqsH5UyTBzmh9YizdsBE,4xWMewm6CYMstu0sPgd9jJ,3VAX2MJdmdqARLSU5hPMpm,\r\nYour Gods and my Gods-do you or I know whi...,The Ugly Duckling,31.0,36
3,51g5viCaYjOW5XO4qX1RCD,4xWMewm6CYMstu0sPgd9jJ,1WJzRtI1ABzV3TPIeJZVvi,\r\nYour Gods and my Gods-do you or I know whi...,Three Blind Mice,0.0,36
4,7EtGJVYZbb2Krgwizn2flB,4xWMewm6CYMstu0sPgd9jJ,65MopnhsXOgYw4RuiA2pGU,\r\nYour Gods and my Gods-do you or I know whi...,The Three Billy Goats Gruff,30.0,36

In [28]:
extended_tracks_df = pd.merge(extended_tracks_df, spotify_artists_df[['artists_id', 'artist_name']], on='artists_id')
extended_tracks_df.head()

,album_id,artists_id,track_id,lyrics,track_name,track_popularity,artist_popularity,artist_name
0,0D3QufeCudpQANOR7luqdr,3mxJuHRn2ZWD5OofvJtDZY,5qljLQuKnNJf4F4vfxQB0V,\r\n\r\nPerhaps I am bound to be restless\r\nA...,Blood,28.0,28,Jesse Markin
1,3wIjGVauUxR4c3NvnQZ0Jo,3mxJuHRn2ZWD5OofvJtDZY,3THTkAwJOsmxgizvYkBNRI,\r\n\r\nMuch better in my day\r\nMuch better i...,Jericho,37.0,28,Jesse Markin
2,1bcqsH5UyTBzmh9YizdsBE,4xWMewm6CYMstu0sPgd9jJ,3VAX2MJdmdqARLSU5hPMpm,\r\nYour Gods and my Gods-do you or I know whi...,The Ugly Duckling,31.0,36,Favorite Kids Stories
3,51g5viCaYjOW5XO4qX1RCD,4xWMewm6CYMstu0sPgd9jJ,1WJzRtI1ABzV3TPIeJZVvi,\r\nYour Gods and my Gods-do you or I know whi...,Three Blind Mice,0.0,36,Favorite Kids Stories
4,7EtGJVYZbb2Krgwizn2flB,4xWMewm6CYMstu0sPgd9jJ,65MopnhsXOgYw4RuiA2pGU,\r\nYour Gods and my Gods-do you or I know whi...,The Three Billy Goats Gruff,30.0,36,Favorite Kids Stories

In [29]:
extended_tracks_df = pd.merge(extended_tracks_df, spotify_albums_df[['album_id', 'album_name']], on='album_id')
extended_tracks_df.head()

,album_id,artists_id,track_id,lyrics,track_name,track_popularity,artist_popularity,artist_name,album_name
0,0D3QufeCudpQANOR7luqdr,3mxJuHRn2ZWD5OofvJtDZY,5qljLQuKnNJf4F4vfxQB0V,\r\n\r\nPerhaps I am bound to be restless\r\nA...,Blood,28.0,28,Jesse Markin,Blood
1,3wIjGVauUxR4c3NvnQZ0Jo,3mxJuHRn2ZWD5OofvJtDZY,3THTkAwJOsmxgizvYkBNRI,\r\n\r\nMuch better in my day\r\nMuch better i...,Jericho,37.0,28,Jesse Markin,Jericho
2,1bcqsH5UyTBzmh9YizdsBE,4xWMewm6CYMstu0sPgd9jJ,3VAX2MJdmdqARLSU5hPMpm,\r\nYour Gods and my Gods-do you or I know whi...,The Ugly Duckling,31.0,36,Favorite Kids Stories,"Storytime Classics, Vol. 2"
3,1bcqsH5UyTBzmh9YizdsBE,4xWMewm6CYMstu0sPgd9jJ,7rT11H4kU8yiq5FAFcd283,\r\nYour Gods and my Gods-do you or I know whi...,My Little Dog,0.0,36,Favorite Kids Stories,"Storytime Classics, Vol. 2"
4,51g5viCaYjOW5XO4qX1RCD,4xWMewm6CYMstu0sPgd9jJ,1WJzRtI1ABzV3TPIeJZVvi,\r\nYour Gods and my Gods-do you or I know whi...,Three Blind Mice,0.0,36,Favorite Kids Stories,"Storytime Classics, Vol. 1"

In [30]:
extended_tracks_df = pd.merge(extended_tracks_df, spotify_albums_df[['album_id', 'release_date']], on='album_id')
extended_tracks_df.head()

,album_id,artists_id,track_id,lyrics,track_name,track_popularity,artist_popularity,artist_name,album_name,release_date
0,0D3QufeCudpQANOR7luqdr,3mxJuHRn2ZWD5OofvJtDZY,5qljLQuKnNJf4F4vfxQB0V,\r\n\r\nPerhaps I am bound to be restless\r\nA...,Blood,28.0,28,Jesse Markin,Blood,2018-05-18
1,3wIjGVauUxR4c3NvnQZ0Jo,3mxJuHRn2ZWD5OofvJtDZY,3THTkAwJOsmxgizvYkBNRI,\r\n\r\nMuch better in my day\r\nMuch better i...,Jericho,37.0,28,Jesse Markin,Jericho,2019-01-25
2,1bcqsH5UyTBzmh9YizdsBE,4xWMewm6CYMstu0sPgd9jJ,3VAX2MJdmdqARLSU5hPMpm,\r\nYour Gods and my Gods-do you or I know whi...,The Ugly Duckling,31.0,36,Favorite Kids Stories,"Storytime Classics, Vol. 2",2011-03-01
3,1bcqsH5UyTBzmh9YizdsBE,4xWMewm6CYMstu0sPgd9jJ,7rT11H4kU8yiq5FAFcd283,\r\nYour Gods and my Gods-do you or I know whi...,My Little Dog,0.0,36,Favorite Kids Stories,"Storytime Classics, Vol. 2",2011-03-01
4,51g5viCaYjOW5XO4qX1RCD,4xWMewm6CYMstu0sPgd9jJ,1WJzRtI1ABzV3TPIeJZVvi,\r\nYour Gods and my Gods-do you or I know whi...,Three Blind Mice,0.0,36,Favorite Kids Stories,"Storytime Classics, Vol. 1",2011-03-01

In [31]:
extended_tracks_df = extended_tracks_df.replace('\n',' ', regex=True)
extended_tracks_df.head(2)

,album_id,artists_id,track_id,lyrics,track_name,track_popularity,artist_popularity,artist_name,album_name,release_date
0,0D3QufeCudpQANOR7luqdr,3mxJuHRn2ZWD5OofvJtDZY,5qljLQuKnNJf4F4vfxQB0V,\r \r Perhaps I am bound to be restless\r Alwa...,Blood,28.0,28,Jesse Markin,Blood,2018-05-18
1,3wIjGVauUxR4c3NvnQZ0Jo,3mxJuHRn2ZWD5OofvJtDZY,3THTkAwJOsmxgizvYkBNRI,\r \r Much better in my day\r Much better in m...,Jericho,37.0,28,Jesse Markin,Jericho,2019-01-25

In [32]:
extended_tracks_df = extended_tracks_df.replace('\r',' ', regex=True)
extended_tracks_df.head(2)

,album_id,artists_id,track_id,lyrics,track_name,track_popularity,artist_popularity,artist_name,album_name,release_date
0,0D3QufeCudpQANOR7luqdr,3mxJuHRn2ZWD5OofvJtDZY,5qljLQuKnNJf4F4vfxQB0V,Perhaps I am bound to be restless Always ...,Blood,28.0,28,Jesse Markin,Blood,2018-05-18
1,3wIjGVauUxR4c3NvnQZ0Jo,3mxJuHRn2ZWD5OofvJtDZY,3THTkAwJOsmxgizvYkBNRI,Much better in my day Much better in my d...,Jericho,37.0,28,Jesse Markin,Jericho,2019-01-25

In [33]:
extended_tracks_df.shape

(77845, 10)

In [34]:
# nothing is missing wooooooo
extended_tracks_df.isnull().mean()

album_id             0.0
artists_id           0.0
track_id             0.0
lyrics               0.0
track_name           0.0
track_popularity     0.0
artist_popularity    0.0
artist_name          0.0
album_name           0.0
release_date         0.0
dtype: float64

In [35]:
extended_tracks_df = extended_tracks_df.drop(['album_id', 'artists_id', 'track_id'], axis=1)
extended_tracks_df.head(2)

,lyrics,track_name,track_popularity,artist_popularity,artist_name,album_name,release_date
0,Perhaps I am bound to be restless Always ...,Blood,28.0,28,Jesse Markin,Blood,2018-05-18
1,Much better in my day Much better in my d...,Jericho,37.0,28,Jesse Markin,Jericho,2019-01-25

In [36]:
extended_tracks_df.shape

(77845, 7)

In [37]:
extended_tracks_df = extended_tracks_df[["release_date", "track_name", "artist_name", "album_name", "lyrics", "track_popularity", "artist_popularity"]]
extended_tracks_df.head(2)

,release_date,track_name,artist_name,album_name,lyrics,track_popularity,artist_popularity
0,2018-05-18,Blood,Jesse Markin,Blood,Perhaps I am bound to be restless Always ...,28.0,28
1,2019-01-25,Jericho,Jesse Markin,Jericho,Much better in my day Much better in my d...,37.0,28

In [38]:
print(len(extended_tracks_df.groupby('release_date')))

6906

In [39]:
# tracks_slang_df = tracks_slang_df.reindex(sorted(tracks_slang_df.columns), axis=1)
extended_tracks_df = extended_tracks_df.sort_values('release_date')
extended_tracks_df.head()

,release_date,track_name,artist_name,album_name,lyrics,track_popularity,artist_popularity
47399,1886,The Knights' Theme,Jason Graves,The Order: 1886 (Video Game Soundtrack),-99,39.0,38
16992,1923,Nobody Knows You When You're Down and Out,Bessie Smith,The Best of Bessie Smith,Once I lived the life of a millionaire Spen...,47.0,46
63360,1926-07-01,Horses - Take 2,George Olsen,"Volume 2, 1925-1926","Five foot two, eyes of blue But oh what tho...",13.0,15
59810,1928,Papa's on the House Top,Leroy Carr,"Whiskey Is My Habit, Good Women Is All I Crave...",-99,36.0,29
53938,1928,"Dark Was the Night, Cold Was the Ground",Blind Willie Johnson,Dark Was The Night (Mojo Workin'- Blues For Th...,"Dark was the night, and cold the ground On ...",50.0,40

In [40]:
# creating tracks_artists_albums_lyrics.csv
extended_tracks_df.to_csv('/Users/iman/CPSC_Courses/CPSC393/CPSC393Final/Data/tracks_artists_albums_lyrics.csv', index = False, header=True)

In [14]:
tracks_slang_df = pd.read_csv("/Users/iman/CPSC_Courses/CPSC393/CPSC393Final/Data/tracks_artists_albums_lyrics.csv")
tracks_slang_df.head()

,release_date,track_name,artist_name,album_name,lyrics,track_popularity,artist_popularity
0,1886,The Knights' Theme,Jason Graves,The Order: 1886 (Video Game Soundtrack),-99,39.0,38
1,1923,Nobody Knows You When You're Down and Out,Bessie Smith,The Best of Bessie Smith,Once I lived the life of a millionaire Spen...,47.0,46
2,1926-07-01,Horses - Take 2,George Olsen,"Volume 2, 1925-1926","Five foot two, eyes of blue But oh what tho...",13.0,15
3,1928,Papa's on the House Top,Leroy Carr,"Whiskey Is My Habit, Good Women Is All I Crave...",-99,36.0,29
4,1928,"Dark Was the Night, Cold Was the Ground",Blind Willie Johnson,Dark Was The Night (Mojo Workin'- Blues For Th...,"Dark was the night, and cold the ground On ...",50.0,40

In [15]:
# data cleaning 
tracks_slang_df['lyrics'] = tracks_slang_df['lyrics'].str.replace('\W', ' ') # Removes punctuation
tracks_slang_df['lyrics'] = tracks_slang_df['lyrics'].str.lower() # making all the words lowercase
tracks_slang_df.head(2)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

,release_date,track_name,artist_name,album_name,lyrics,track_popularity,artist_popularity
0,1886,The Knights' Theme,Jason Graves,The Order: 1886 (Video Game Soundtrack),99,39.0,38
1,1923,Nobody Knows You When You're Down and Out,Bessie Smith,The Best of Bessie Smith,once i lived the life of a millionaire spen...,47.0,46

In [16]:
tracks_slang_df = tracks_slang_df.drop(tracks_slang_df.index[range(19505)])
tracks_slang_df.head(2)

,release_date,track_name,artist_name,album_name,lyrics,track_popularity,artist_popularity
19505,2010,Atmosphere - 2010 Remastered Version,Joy Division,Substance,it s early morning the sun comes out las...,51.0,66
19506,2010,Hombre en U,Divididos,Amapola del 66,al sol no va más vuelve todo hacia el verdi...,40.0,62

In [17]:
tracks_slang_df = tracks_slang_df.iloc[::2, :]
tracks_slang_df = tracks_slang_df.iloc[::2, :]
tracks_slang_df = tracks_slang_df.iloc[::2, :]
tracks_slang_df.head(2)

,release_date,track_name,artist_name,album_name,lyrics,track_popularity,artist_popularity
19505,2010,Atmosphere - 2010 Remastered Version,Joy Division,Substance,it s early morning the sun comes out las...,51.0,66
19513,2010,My Best Days Are Ahead Of Me,Danny Gokey,My Best Days,blowing out the candles on another birthday...,38.0,57

In [18]:
tracks_slang_df.shape

(7293, 7)

In [19]:
# creating tracks_artists_albums_lyrics.csv
tracks_slang_df.to_csv('/Users/iman/CPSC_Courses/CPSC393/CPSC393Final/Data/2010_to_2019.csv', index = False, header=True)
years_2010_to_2019_df = pd.read_csv("/Users/iman/CPSC_Courses/CPSC393/CPSC393Final/Data/2010_to_2019.csv")
years_2010_to_2019_df.head()

,release_date,track_name,artist_name,album_name,lyrics,track_popularity,artist_popularity
0,2010,Atmosphere - 2010 Remastered Version,Joy Division,Substance,it s early morning the sun comes out las...,51.0,66
1,2010,My Best Days Are Ahead Of Me,Danny Gokey,My Best Days,blowing out the candles on another birthday...,38.0,57
2,2010,El Amor Que Perdimos,Prince Royce,Number 1's,letra de el amor que perdimos anoche so...,54.0,82
3,2010,Carry on Wayward Son,Kansas,The Essential Kansas,carry on my wayward son there ll be peace...,65.0,68
4,2010,Aves de Agua,Aaron Cruz Trío,Eco,99,24.0,16

In [20]:
# creating vocabulary from training data
tracks_slang_df['lyrics'] = tracks_slang_df['lyrics'].str.split()
vocabulary = []
for lyrics in tracks_slang_df['lyrics']:
   for word in lyrics:
      vocabulary.append(word)
vocabulary = list(set(vocabulary)) # only count the number of unique words
print(len(vocabulary))

89520

In [21]:
# each word in each sms_message will be an x-value
word_counts_per_lyrics = {unique_word: [0] * len(tracks_slang_df['lyrics']) for unique_word in vocabulary}

for index, lyrics in enumerate(tracks_slang_df['lyrics']):
   for word in lyrics:
      word_counts_per_lyrics[word][index] += 0
word_counts = pd.DataFrame(word_counts_per_lyrics)
word_counts

,tulkaa,kardashian,silmistäsi,n7sad,frankie,unsrer,chum,흩어진,slamming,massi,...,reciban,préférer,styles,tembé,בדיל,naru,hustlin,알았었지,testical,repères
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7288,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7289,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7290,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7291,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7292,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0